### ISSUE TITLE
"Hybrid" tooltip info is not matching designs

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#1214]
**Describe the bug**
"Hybrid" tooltip info is not matching designs

**To Reproduce**
1. Go to https://cryoetdataportal.czscience.com/depositions/10309
2. Hover on [i] next to Hybrid
3. Compare to Design

**Screenshots**
<img width="1206" alt="image" src="https://github.com/user-attachments/assets/797e02e1-c932-4c40-9b5e-4e3acb2cf9ce">

**Desktop (please complete the following information):**
- OS: MacOS Sonoma v14.7
- Browser Chrome

**Comment by junxini** [comment]
@Janeece the source of truth tooltip text is [here](https://docs.google.com/spreadsheets/d/1QEPiDcjGJYWSZXsbRjwHd9aeZjbk_tvv2UQ4DKyMwxk/edit?gid=339544814#gid=339544814). not sure what the best way is to have the designs match or even referenced to SOT if that's easier?

**Comment by Janeece** [comment]
@junxini TBH, its more practical and consistent to have the team reference the copy SOT than the designs when it comes to checking if copy is correct. 

- Design specs can refer to the SOT, but we should also find an easy place for team to find it in cases where design misses something. 
- We can add general link to SOT in masterfiles
- Requests to update masterfile copy can be added to the design board, but they will be low priority.

**Comment by dgmccart** [comment]
The tooltip looks right to me! We opted not to have documentation linked out because the metadata on the annotation info panel provides a more detailed description of the method, and there isn't a concise set of methods to describe in documentation. 

As far as SOT goes, I can work with Janeece on future designs to make sure the copy SOT is linked or correct in the designs. But, it seems like in this case everything went to plan, so we can probably close this issue.

**Comment by junxini** [comment]
sounds good, thank you both for your quick responses. i'll be closing this ticket
