### ISSUE TITLE
Datasets and Depositions info icon is missing

### ISSUE THREAD

**Issue by lauramarcos** [chanzuckerberg/cryoet-data-portal#1216]
**Describe the bug**
Datasets and Depositions info icon is missing in depositions page

**To Reproduce**
1. Go to ['...'](https://cryoetdataportal.czscience.com/browse-data/depositions)
2. Pay attention to "Depositions" page title
3. Compare to design

**Screenshots**
<img width="912" alt="image" src="https://github.com/user-attachments/assets/09798828-97f2-41a8-98ba-b3685c07c384">

<img width="946" alt="image" src="https://github.com/user-attachments/assets/fd230796-8281-43b7-a62b-bfd23f09471b">

**Desktop (please complete the following information):**

**Comment by junxini** [comment]
@lauramarcos we ended up going with the banner with the text instead of the tooltip. @Janeece i think there might be 2 designs circulating, maybe we remove the bug tag for this ticket and replace with a design ticket tag?

**Comment by Janeece** [comment]
The [masterfiles](https://www.figma.com/files/785978749374268122/project/174360582) only reflects the banner. This should be treated as SOT for depositions designs, except for a couple of educational tooltips that are on hold. 

In the original [spec](https://www.figma.com/design/Rrr54QysCLa14vOnQcmejb/Janeece---Annotation-Depositions?node-id=3225-59818&t=ifklD3cz2XpRx2bg-1)
- The old design for tooltip in the header was labeled as archived, I've moved it out of the spec since this was confusing
- Anything that has the "completed" checkmark is in the masterfile & on prod, anything with the Green "ready for dev" is not (just the [education add ons](https://www.figma.com/design/Rrr54QysCLa14vOnQcmejb/Janeece---Annotation-Depositions?node-id=3381-74782&t=ifklD3cz2XpRx2bg-1)). 
<img width="118" alt="Screenshot 2024-10-11 at 12 01 42 PM" src="https://github.com/user-attachments/assets/7add45c0-ce8b-4b3a-895c-2b76aa2b84fd">
<img width="128" alt="Screenshot 2024-10-11 at 12 01 35 PM" src="https://github.com/user-attachments/assets/41eb531a-aef3-4adf-93cd-03308d8d0f1e">
