### ISSUE TITLE
Neuroglancer not working, showing "no zarr metadata found" error

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#306]
When clicking on View Tomogram, neuroglancer seems to be having trouble loading dataset 10007

<img width="1728" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/98626158/7adc72d8-7240-4034-b5e4-aa154362c731">

**Comment by junxini** [comment]
@uermel @manasaV3 @jgadling any idea if this is an issue with NG or something caused by the backend data?

**Comment by uermel** [comment]
I'm a little confused by this one. 

For that run, "Voxelspacing13.48" should not exist, which is why that zarr-link would not work. With the proper value "Voxelspacing7.840" it loads fine for me (because that file actually exists). When I click on 'View Tomogram' [here](https://cryoetdataportal.czscience.com/runs/10717) the correct voxelspacing is used. 

Potentially this bug is outdated after the reimport?

<img width="772" alt="image" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/6641113/97040b2a-0beb-4719-99c0-bbe4924b5d00">

**Comment by junxini** [comment]
nevermind, I rechecked and wasn't able to reproduce either! will close this bug
