### ISSUE TITLE
Run Name is cut short in the Runs Table - Single Dataset Page 

### ISSUE THREAD

**Issue by junxini** [chanzuckerberg/cryoet-data-portal#389]
Bug description: When run names are long, the title gets cutoff because the column width is too narrow

Expected Result: wider column to decrease likelihood of the run name getting cutoff

![image](https://github.com/chanzuckerberg/cryoet-data-portal/assets/98626158/5b7b6b83-8335-4c63-95b7-0a60a7903b09)

Link: https://cryoetdataportal.czscience.com/datasets/10004

See Janeece's comment below for design specs

**Comment by Janeece** [comment]
@junxini @manasaV3 @codemonkey800 @kne42 

Here is the updated spec for the runs table spacing (just frame 1.10 Min/Max sizing, it's marked for this ticket/ready for dev):
https://www.figma.com/file/0UT1iyRVRkIdH4qLfh8JDd/3---Single-Dataset?type=design&node-id=94%3A9403&mode=dev

- The pink text with "update" in bold at the end are the changes from the original spec. 
  - Run Column: 
     - Remove max width
     - changed min width to 400px 
     - defined Run name text wrap up to max content height (100px), then overflow
  - Button Column: 
     - Add 300px max width
- These changes favor more space for the run name to minimize instances of cut-off. Some run tables will have a large gap of space because they are short, but I think as a stop gap to a better overflow solution, its better to have too much space than important info being cut off. 

Let me know if there are any questions or concerns!

<img width="1481" alt="Screenshot 2024-01-22 at 4 03 15 PM" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/63013360/9f2f2cbb-2694-465c-a633-3f524b103a84">
