### ISSUE TITLE
Annotation Author shows up twice in annotations table and "more info"-panel when they are both primary and corresponding author

### ISSUE THREAD

**Issue by uermel** [chanzuckerberg/cryoet-data-portal#752]
**Describe the bug**
When there is only a single Author for an annotation, who is both primary author and corresponding author, the author shows up twice in the table and the more info panel.

**To Reproduce**
- visit https://cryoetdataportal.czscience.com/runs/1147
- inspect author list of 15432 in table
- inspect author list of 15432 in more info panel 

**Screenshots**
<img width="1263" alt="Screenshot 2024-05-23 at 1 52 02 PM" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/6641113/c388dfe4-3add-43d1-84c4-8cde721f6d2e">

<img width="460" alt="Screenshot 2024-05-23 at 1 52 43 PM" src="https://github.com/chanzuckerberg/cryoet-data-portal/assets/6641113/e7ccf9ec-4d4d-435f-b356-0bacd561196a">

**Desktop (please complete the following information):**
 - OS: MacOS Sonoma 14.5
 - Browser: Chrome

**Additional context**

**Comment by junxini** [comment]
@kne42 here's the summary of the changes based on our discussion during sprint planning:

1. go to https://cryoetdataportal.czscience.com/runs/1147
2. for annotation 17429
  - the author list in the table to list "Utz Heinrich Ermel, ..."
  - the author list in the metadata to list 
![Screenshot 2024-06-06 at 10 58 23 AM](https://github.com/chanzuckerberg/cryoet-data-portal/assets/98626158/6d3181be-d24f-456f-ad6f-61f99e636b91)

3. for annotation 15432
  - the author list in the table to list "Mohammed Kaplan"
  - the author list in the metadata to remove the repeated name (i.e. Mohammed Kaplan to remain bolded with mail icon)

**Comment by bchu1** [comment]
@junxini Do these changes apply to the datasets table as well?

i.e. this

![image](https://github.com/user-attachments/assets/f0dc1182-e8c9-440e-a8b3-ddfb1c6c7421)


would become this

![image](https://github.com/user-attachments/assets/8705521e-973f-43a5-9e0e-89d3e3705bc4)

**Comment by junxini** [comment]
@bchu1 good callout on the datasets table. the example you provided removed all corresponding authors (i.e. the names to the right of the "...") which would not be the behavior we're looking for. 

it applies to scenarios where the same author is listed as both the primary (meaning bolded) and corresponding (has an envelope icon). Instead of showing their name twice, their name would be shown once. 

based on your screenshot, i think only the first row (dataset 10003) fits that description. Tegunov Dimitry's name should be removed after the "...". 

when clicking into the single dataset page, it would look like this:


![image](https://github.com/user-attachments/assets/0a83d519-e8e1-421b-933b-254028dc7648)
