### ISSUE TITLE
Flakey unittests for client

### ISSUE THREAD

**Issue by Bento007** [chanzuckerberg/cryoet-data-portal#942]
**Describe the bug**
GHA job test-client-python is flakey.
### Error
```
>           raise MaxRetryError(_pool, url, error or ResponseError(cause))
E           urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /v1/graphql (Caused by ProtocolError('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))
```
**To Reproduce**
open a PR and wait for *test-client-python* to run.

**Screenshots**
![Screenshot 2024-07-25 at 12 07 53 PM](https://github.com/user-attachments/assets/13bbe62c-8dde-4931-b180-29fdd58ef7f4)

**Comment by andy-sweet** [comment]
I'm running into this more frequently in https://github.com/chanzuckerberg/cryoet-data-portal/pull/1008 where I'm adding a few more tests that hit the fake endpoint used for testing.

@Bento007 : not sure if you already start working on this, but as these tests are some of the first tests to run under `pytest`, I wondered if adding `--wait` to `docker compose up -d` might be enough to fix the flakiness here?

If I understood the docker compose docs correct that should wait until all containers are healthy/running, otherwise the only guarantee is that have started.

**Comment by andy-sweet** [comment]
Unsure how long the logs will last, but here's an example of a failed run on my branch: https://github.com/chanzuckerberg/cryoet-data-portal/actions/runs/10427079368/job/28881156801?pr=1008#step:5:1134

**Comment by andy-sweet** [comment]
Since it would be good to fix this before merging https://github.com/chanzuckerberg/cryoet-data-portal/pull/1008 , I'm going to make a PR to try to fix this.
